In [152]:
import requests
import csv
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

## Select landing, month, year

In [175]:
landing_dic = {'fishermans':['fishermans_landing','22'],\
          'seaforth':['seaforth_sportfishing','20'],\
           'point_loma':['point_loma_sportfishing','23']}
month = 5
year = 2022
landing = landing_dic['point_loma']

# month = 4
# month = str(month+1)
# URL = 'https://www.sandiegofishreports.com/landings/'+landing[0]+'.php?landing_id='+landing[1]+'&month='+month+'&year='+year+'#historicals'
# page = requests.get(URL)
# soup = BeautifulSoup(page.content,'html.parser')
# tb_set = soup.find_all('tbody')

#### Grab data for YYYY-MM

In [201]:
def get_df_yyyymm(year,month,landing):
    month = str(month)
    year = str(year)
    URL = 'https://www.sandiegofishreports.com/landings/'+landing[0]+'.php?landing_id='+landing[1]+'&month='+month+'&year='+year+'#historicals'
    page = requests.get(URL)
    soup = BeautifulSoup(page.content,'html.parser')
    tb_set = soup.find_all('tbody')
    # first table is daily landing counts
    table_daily = tb_set[0]
    # tr finds table rows
    rows = table_daily.find_all('tr') 
    rows = rows[2:-1]

    df = pd.DataFrame(columns = ['Date', 'Boats', 'Anglers','Fish count'])
    for row in rows:
        row_text = row.text.split('\n')
        rwo_text = row_text[1:-1] # remove top and bottom row
        date_text = rwo_text[0].split() # convert "June" to "Jun"
        date_text = date_text[0][:3] + ' ' + date_text[1] + ' ' + date_text[2] # convert "June" to "Jun"
        trip_stats = [datetime.strptime(date_text, '%b %d, %Y')]
        for item in rwo_text[1:3]:
            trip_stats.append(int(item.split()[0]))
        trip_stats.append(rwo_text[-1])
        df.loc[len(df.index)] = trip_stats
    return df

#### Process fish count

In [ ]:
def proc_fish_count(df):

In [202]:
months = [6]
df = pd.DataFrame([]);
for mm in months:
    df = pd.concat([df,get_df_yyyymm(2022,mm,landing)], axis = 0)
df.head()

,Date,Boats,Anglers,Fish count
0,2022-06-01,3,67,"23 Rockfish, 20 Bluefin Tuna, 7 Whitefish, 1 C..."
1,2022-06-02,2,26,"47 Rockfish, 16 Yellowtail, 15 Calico Bass, 7 ..."
2,2022-06-03,4,92,"86 Bluefin Tuna, 71 Rockfish, 42 Whitefish, 34..."
3,2022-06-04,4,101,"106 Bluefin Tuna, 32 Rockfish, 27 Calico Bass,..."
4,2022-06-05,4,106,"118 Bluefin Tuna, 40 Calico Bass, 16 Rockfish,..."

In [179]:
landing_dic = {'fishermans':['fishermans_landing','22'],\
          'seaforth':['seaforth_sportfishing','20'],\
           'point_loma':['point_loma_sportfishing','23']}
month = '7'
year = '2019'
landing = landing_dic['point_loma']

# write to csv
# csv_file = open(landing[0]+'_'+year+'_'+month+'.csv','w', newline='')
csv_file = open(landing[0]+'_'+year+'.csv','w', newline='')
csv_writer = csv.writer(csv_file)

for month in range(12):
    month = str(month+1)
    URL = 'https://www.sandiegofishreports.com/landings/'+landing[0]+'.php?landing_id='+landing[1]+'&month='+month+'&year='+year+'#historicals'
    page = requests.get(URL)
    soup = BeautifulSoup(page.content,'lxml')
    tb_set = soup.find_all('tbody')

    # each fish count category
    fish_kinds = ['Bluefin','Yellowfin','Yellowtail','Barracuda','Calico']
    # first table is daily landing counts
    table_daily_landing_count = tb_set[0]
    # tr finds table rows
    rows = table_daily_landing_count.find_all('tr') 
    rows = rows[:-1]

    # write header
    row_text = rows[1].text.split('\n')[1:-1]
    row_text = row_text[:-1] + fish_kinds  # add fish kinds
    if month == '1': csv_writer.writerow(row_text)

    for row in rows[2:]:
        row_text = row.text.split('\n')[1:-1]

        # find counts for different fish
        raw_fish_counts = row_text[-1].replace(',','').split()
        fish_counts = ['0']*len(fish_kinds)
        for ii in range(len(fish_counts)):
            for jj in range(len(raw_fish_counts)):
                if fish_kinds[ii] in raw_fish_counts[jj]:
                    fish_counts[ii] = raw_fish_counts[jj-1]

        row_text = row_text[:-1] + fish_counts

        # clean some text such as '5 boats' being '5'
        if len(row_text) > 2:
            row_text[1] = row_text[1].split()[0]
            row_text[2] = row_text[2].split()[0]
        csv_writer.writerow(row_text)

csv_file.close()

In [167]:
# each fish count category
month = '2'
fish_kinds = ['Bulefin','Yellowfin','Yellowtail','Barracuda','Calico','Lingcod','Rockfish']
# first table is daily landing counts
table_daily_landing_count = tb_set[0]
# tr finds table rows
rows = table_daily_landing_count.find_all('tr') 

# write to csv
csv_file = open(landing[0]+'_'+year+'_'+month+'.csv','w', newline='')
csv_writer = csv.writer(csv_file)
# write header
row_text = rows[1].text.split('\n')[1:-1]
row_text = row_text[:-1] + fish_kinds  # add fish kinds
csv_writer.writerow(row_text)
    
for row in rows[2:-1]:
    row_text = row.text.split('\n')[1:-1]
    
#     # find counts for different fish
#     raw_fish_counts = row_text[-1].split(', ')
#     fish_counts = ['0']*len(fish_kinds)
#     for ii in range(len(fish_counts)):
#         for jj in range(len(raw_fish_counts)):
#             if fish_kinds[ii] in raw_fish_counts[jj]:
#                 fish_counts[ii] = raw_fish_counts[jj-1]
    
#     row_text = row_text[:-1] + fish_counts
    
    # clean some text such as '5 boats' being '5'
    if len(row_text) > 2:
        row_text[1] = row_text[1].split()[0]
        row_text[2] = row_text[2].split()[0]
    csv_writer.writerow(row_text)

csv_file.close()